language: java
before_install:
  - chmod +x mvnw
os:
  - linux
#addons:
  postgresql: '13.2'
#env:
#  global:
#    - PGUSER=postgres
#    - PGPASSWORD=super123
#    - PGPORT=5432
before_script:
  - sudo psql -p 5432 -U postgres -c 'create database testsystem;'
script:
 - mvn clean install
 - mvn test
