language: java
before_install:
  - chmod +x mvnw
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
sudo: true
jdk: openjdk11
os:
  - linux
dist: xenial
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
  - PGPORT=5433
  - PGUSER=travis
services:
  - postgresql
before_script:
  - psql -c 'create database cosc2101;' -U postgres
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'super123'"
install:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#script:
# - mvn clean verify


