language: java
#before_install:
#  - chmod +x mvnw
jdk: openjdk11
os:
  - linux
dist: xenial
sudo: enabled
addons:
  postgresql: "10"
#env:
#  global:
#  - PGPORT=5433
#  - PGUSER=travis
before_script:
  - psql -c 'create database cosc2101;' -U postgres
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'super123'"
services:
  - postgresql
install:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#script:
# - mvn clean verify


