language: java
before_install:
  - chmod +x mvnw
services:
  - postgresql
os:
  - linux
addons:
  postgresql: '13.2'
env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=super123
    - PGPORT=5432
before_script:
  - psql -c 'create database testsystem' -U postgres
script:
 - mvn clean install
 - mvn test
