language: java
dist: trusty
jdk:
 - openjdk11
before_install:
  - chmod +x mvnw
os:
  - linux
sudo: enabled
addons:
  postgresql: "13.3"
before_script:
  - psql -c "create database testsystem;" -U postgres
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'super123'"
#services:
#  - postgresql
#script:
# - mvn clean install
# - mvn test
