language: java
before_install:
  - chmod +x mvnw
  - "if [ ! -z $PGVERSION ]; then sudo cp /etc/postgresql/{9.6,$PGVERSION}/main/pg_hba.conf; fi"
  - "if [ ! -z $PGVERSION ]; then sudo service postgresql restart $PGVERSION; fi"
sudo: true
jdk: openjdk11
os:
  - linux
dist: xenial
addons:
    postgresql: "12"
    apt:
      packages:
            - postgresql-12
            - postgresql-client-12
            - postgresql-server-dev-12
            - postgresql-client-common
            - postgresql-common
env:
   PGPORT: "5432"
   PGVERSION: 12
#env:
#  global:
#  - PGPORT=5433
#  - PGUSER=travis
services:
  - postgresql
before_script:
  - psql -c 'create database cosc2101;' -U postgres
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'super123'"
install:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#script:
# - mvn clean verify


